/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Analysis Page
 *
 * This page displays the results of a completed portfolio analysis job.
 * It can:
 *  - Load a specific job by `job_id` (from the query string), or
 *  - Automatically find and load the latest completed job if no `job_id` is given.
 *
 * The UI provides:
 *  - A rich Markdown-based overview report
 *  - Dynamic charts generated by the Charter agent (via Recharts)
 *  - A retirement projection view rendered from Markdown
 */

import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { useAuth } from "@clerk/nextjs";
import ReactMarkdown from "react-markdown";
import type { Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkBreaks from "remark-breaks";
import {
  PieChart,
  Pie,
  Cell,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import Layout from "../components/Layout";
import { apiRequest } from "../lib/api";
import Head from "next/head";

/**
 * Job
 *
 * Represents a full analysis job including optional payloads from
 * different agents (report, charts, retirement) and error information.
 */
interface Job {
  id: string;
  created_at: string;
  status: string;
  job_type: string;
  report_payload?: {
    agent: string;
    content: string;
    generated_at: string;
  };
  // Charter stores charts with dynamic keys and arbitrary payload structures
  charts_payload?: Record<string, any> | null;
  retirement_payload?: {
    agent: string;
    analysis: string;
    generated_at: string;
  };
  error_message?: string;
}

/**
 * JobListItem
 *
 * Lightweight representation of a job used when listing and
 * selecting the latest completed job.
 */
interface JobListItem {
  id: string;
  created_at: string;
  status: string;
  job_type: string;
}

/**
 * TabType
 *
 * Controls which main section of the analysis page is visible.
 */
type TabType = "overview" | "charts" | "retirement";

/**
 * COLORS
 *
 * Shared colour palette used to render Recharts chart components.
 */
const COLORS = [
  "#209DD7", // primary
  "#753991", // AI accent
  "#FFB707", // accent
  "#062147", // dark
  "#60A5FA", // light blue
  "#A78BFA", // light purple
  "#FBBF24", // yellow
  "#34D399", // green
  "#F87171", // red
  "#94A3B8", // gray
];

/**
 * Format numeric values as GBP currency (2 decimal places).
 */
const formatCurrencyGBP = (value: number): string =>
  new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);

const formatCurrencyGBPCompact = (value: number): string =>
  new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    notation: "compact",
    maximumFractionDigits: 1,
  }).format(value);

const truncateLabel = (value: string, max = 14): string =>
  value.length > max ? `${value.slice(0, Math.max(0, max - 1))}…` : value;

/**
 * Convert keys like "fixed_income" or "cash" into "Fixed Income" / "Cash".
 */
const formatLabelName = (name: string): string =>
  name
    .replace(/_/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
  .join(" ");

/**
 * Shared Markdown renderer styles.
 *
 * Keeps Overview + Retirement tabs visually consistent.
 */
const MARKDOWN_COMPONENTS: Components = {
  h1: ({ children, ...props }) => (
    <h1
      {...props}
      className="text-3xl font-bold mb-4 text-gray-900 border-b border-gray-300/40 pb-2"
    >
      {children}
    </h1>
  ),
  h2: ({ children, ...props }) => (
    <h2
      {...props}
      className="text-2xl font-semibold mb-3 text-gray-800 mt-6 border-b border-gray-200/40 pb-2"
    >
      {children}
    </h2>
  ),
  h3: ({ children, ...props }) => (
    <h3 {...props} className="text-xl font-medium mb-2 text-gray-700 mt-4">
      {children}
    </h3>
  ),
  ul: ({ children, ...props }) => (
    <ul {...props} className="list-disc ml-6 mb-4 space-y-1">
      {children}
    </ul>
  ),
  ol: ({ children, ...props }) => (
    <ol {...props} className="list-decimal ml-6 mb-4 space-y-1">
      {children}
    </ol>
  ),
  li: ({ children, ...props }) => (
    <li {...props} className="text-gray-700">
      {children}
    </li>
  ),
  p: ({ children, ...props }) => (
    <p {...props} className="mb-4 text-gray-700 leading-relaxed">
      {children}
    </p>
  ),
  table: ({ children, ...props }) => (
    <div className="overflow-x-auto mb-6">
      <table {...props} className="w-full border-collapse">
        {children}
      </table>
    </div>
  ),
  thead: ({ children, ...props }) => (
    <thead {...props} className="bg-gray-100">
      {children}
    </thead>
  ),
  th: ({ children, ...props }) => (
    <th
      {...props}
      className="p-3 text-left font-semibold border border-gray-300"
    >
      {children}
    </th>
  ),
  td: ({ children, ...props }) => (
    <td {...props} className="p-3 border border-gray-300">
      {children}
    </td>
  ),
  strong: ({ children, ...props }) => (
    <strong {...props} className="font-semibold text-gray-900">
      {children}
    </strong>
  ),
  blockquote: ({ children, ...props }) => (
    <blockquote
      {...props}
      className="border-l-4 border-primary pl-4 my-4 italic text-gray-600"
    >
      {children}
    </blockquote>
  ),
};

const MarkdownPanel = ({ content }: { content: string }) => (
  <div className="prose prose-lg max-w-none">
    <ReactMarkdown
      remarkPlugins={[remarkGfm, remarkBreaks]}
      components={MARKDOWN_COMPONENTS}
    >
      {content}
    </ReactMarkdown>
  </div>
);

/**
 * Analysis
 *
 * Main page component that:
 *  - Loads a specific analysis job (or the latest completed one)
 *  - Handles loading, empty, in-progress, and failed states
 *  - Renders three main tabs: Overview (Markdown), Charts (Recharts), Retirement projection
 */
export default function Analysis() {
  const router = useRouter();
  const { getToken } = useAuth();
  const { job_id } = router.query;

  const [job, setJob] = useState<Job | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<TabType>("overview");
  const [fetchingLatest, setFetchingLatest] = useState(false);

  /**
   * loadJob
   *
   * Fetches the full details of a single job from the backend.
   */
  useEffect(() => {
    const loadJob = async (jobId: string) => {
      try {
        const token = await getToken();
        if (!token) {
          setLoading(false);
          return;
        }
        const jobData = await apiRequest<Job>(`/api/jobs/${jobId}`, token);
        setJob(jobData);
      } catch (error) {
        console.error("Error fetching job:", error);
      } finally {
        setLoading(false);
      }
    };

    /**
     * loadLatestJob
     *
     * When no `job_id` is supplied, this function:
     *  - Fetches all jobs
     *  - Finds the latest completed job
     *  - Loads full details for that job
     *  - Updates the URL to include the job_id (shallow replace)
     */
    const loadLatestJob = async () => {
      setFetchingLatest(true);
      try {
        const token = await getToken();
        if (!token) {
          setLoading(false);
          return;
        }
        const data = await apiRequest<{ jobs?: JobListItem[] }>("/api/jobs", token);
        const jobs: JobListItem[] = data.jobs || [];

        const latestCompletedJob = jobs
          .filter((j) => j.status === "completed")
          .sort(
            (a, b) =>
              new Date(b.created_at).getTime() -
              new Date(a.created_at).getTime(),
          )[0];

        if (latestCompletedJob) {
          await loadJob(latestCompletedJob.id);

          // Update URL without full page reload
          router.replace(`/analysis?job_id=${latestCompletedJob.id}`, undefined, {
            shallow: true,
          });
        } else {
          setLoading(false);
        }
      } catch (error) {
        console.error("Error fetching latest job:", error);
        setLoading(false);
      } finally {
        setFetchingLatest(false);
      }
    };

    if (job_id) {
      // Explicit job_id provided in query
      loadJob(job_id as string);
    } else if (router.isReady) {
      // Router is ready but no job_id â€“ fetch the latest completed analysis
      loadLatestJob();
    }
  }, [job_id, router.isReady, getToken, router]);

  /**
   * formatDate
   *
   * Formats a date string into a long, human-readable format
   * suitable for a "Completed on" label.
   */
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  /**
   * Global loading state: skeleton placeholder while fetching job data.
   */
  if (loading) {
    return (
      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-white rounded-lg shadow px-8 py-12 text-center">
              <div className="animate-pulse">
                <div className="h-8 bg-gray-200 rounded w-1/3 mx-auto mb-4" />
                <div className="h-4 bg-gray-200 rounded w-1/2 mx-auto" />
              </div>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  /**
   * No job available:
   *  - Either there are no completed jobs
   *  - Or the latest job could not be loaded
   */
  if (!job) {
    return (
      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-white rounded-lg shadow px-8 py-12 text-center">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                {fetchingLatest
                  ? "Loading Latest Analysis..."
                  : "No Analysis Available"}
              </h2>
              <p className="text-gray-600 mb-6">
                {fetchingLatest
                  ? "Please wait while we load your latest analysis."
                  : "You have not completed any analyses yet. Start a new analysis to see results here."}
              </p>
              {!fetchingLatest && (
                <button
                  onClick={() => router.push("/advisor-team")}
                  className="px-6 py-3 bg-primary text-white rounded-lg hover:bg-blue-600 font-semibold"
                >
                  Start New Analysis
                </button>
              )}
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  /**
   * In-progress job state:
   *  - Show a status message and simple animated indicators
   */
  if (job.status === "running" || job.status === "pending") {
    return (
      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-white rounded-lg shadow px-8 py-12 text-center">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                Analysis In Progress
              </h2>
              <p className="text-gray-600 mb-6">
                Your analysis is still being processed. Please check back in a
                few moments.
              </p>
              <div className="flex justify-center space-x-2 mb-6">
                <div className="w-3 h-3 bg-ai-accent rounded-full animate-pulse" />
                <div className="w-3 h-3 bg-ai-accent rounded-full animate-pulse delay-75" />
                <div className="w-3 h-3 bg-ai-accent rounded-full animate-pulse delay-150" />
              </div>
              <button
                onClick={() => window.location.reload()}
                className="px-6 py-3 bg-primary text-white rounded-lg hover:bg-blue-600 font-semibold"
              >
                Refresh
              </button>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  /**
   * Failed job state:
   *  - Show a failure summary and any error details returned by the backend
   */
  if (job.status === "failed") {
    return (
      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-white rounded-lg shadow px-8 py-12">
              <h2 className="text-2xl font-bold text-red-600 mb-4">
                Analysis Failed
              </h2>
              <p className="text-gray-600 mb-4">
                The analysis encountered an error and could not be completed.
              </p>
              {job.error_message && (
                <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
                  <p className="text-sm text-red-800">{job.error_message}</p>
                </div>
              )}
              <button
                onClick={() => router.push("/advisor-team")}
                className="px-6 py-3 bg-primary text-white rounded-lg hover:bg-blue-600 font-semibold"
              >
                Try Another Analysis
              </button>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  /**
   * renderOverview
   *
   * Renders the "Overview" tab using Markdown content from the
   * financial planner agent's report payload.
   */
  const renderOverview = () => {
    const report = job?.report_payload?.content;
    if (!report) {
      return (
        <div className="text-center py-12 text-gray-500">
          No portfolio report available.
        </div>
      );
    }

    return <MarkdownPanel content={report} />;
  };

  /**
   * renderCharts
   *
   * Renders the "Charts" tab using the dynamic charts payload from
   * the Charter agent. It:
   *  - Infers chart type when not explicitly provided
   *  - Supports pie/donut, bar, horizontal bar, and line charts
   *  - Provides responsive containers and formatted tooltips
   */
  const renderCharts = () => {
    const chartsPayload = job?.charts_payload;
    if (!chartsPayload || Object.keys(chartsPayload).length === 0) {
      return (
        <div className="text-center py-12 text-gray-500">
          No chart data available.
        </div>
      );
    }

    // Helper to turn a key like "sector_allocation" into "Sector Allocation"
    const formatTitle = (key: string): string => formatLabelName(key);

    /**
     * getChartType
     *
     * Determines which chart type to use based on:
     *  - Explicit `type` field from the charter agent (if present)
     *  - Fallback heuristics based on data shape
     */
    const getChartType = (
      chartData: any,
    ): "pie" | "donut" | "bar" | "horizontalBar" | "line" => {
      if (chartData.type) {
        const supportedTypes = ["pie", "donut", "bar", "horizontalBar", "line"];
        if (supportedTypes.includes(chartData.type)) {
          return chartData.type;
        }

        const typeMap: Record<
          string,
          "pie" | "donut" | "bar" | "horizontalBar" | "line"
        > = {
          column: "bar",
          area: "line",
        };

        if (typeMap[chartData.type]) {
          return typeMap[chartData.type];
        }
      }

      // Simple heuristics when no explicit type is given
      if (chartData.data?.[0]?.date || chartData.data?.[0]?.year) return "line";
      if (chartData.data?.length <= 10 && chartData.data?.[0]?.value)
        return "pie";

      return "bar";
    };

    const chartItems = Object.entries(chartsPayload)
      .map(([key, chartData]) => {
        if (!chartData?.data || chartData.data.length === 0) return null;

        const chartType = getChartType(chartData);
        const title = chartData.title || formatTitle(key);
        const isBar = chartType === "bar" || chartType === "horizontalBar";

        return { key, chartData, chartType, title, isBar };
      })
      .filter(Boolean) as Array<{
      key: string;
      chartData: any;
      chartType: "pie" | "donut" | "bar" | "horizontalBar" | "line";
      title: string;
      isBar: boolean;
    }>;

    const barCharts = chartItems.filter((item) => item.isBar);
    const otherCharts = chartItems.filter((item) => !item.isBar);

    const orderedCharts = [
      ...barCharts.slice(0, 1),
      ...otherCharts,
      ...barCharts.slice(1),
    ];

    return (
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {orderedCharts.map(({ key, chartData, chartType, title, isBar }) => {
          const plotHeight = isBar ? 320 : 300;
          return (
            <div
              key={key}
              className={`bg-white rounded-lg p-6 border border-gray-200 ${
                isBar ? "lg:col-span-2" : ""
              }`}
            >
              <h3 className="text-xl font-semibold mb-4 text-gray-800">
                {title}
              </h3>
              <ResponsiveContainer width="100%" height={plotHeight}>
                {chartType === "pie" || chartType === "donut" ? (
                  <PieChart>
                    <Pie
                      data={chartData.data}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={false}
                      outerRadius={100}
                      innerRadius={chartType === "donut" ? 60 : 0}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {chartData.data.map((entry: any, idx: number) => (
                        <Cell
                          key={`cell-${idx}`}
                          fill={entry.color || COLORS[idx % COLORS.length]}
                        />
                      ))}
                    </Pie>
                    <Tooltip
                      formatter={(value: number | string) =>
                        typeof value === "number"
                          ? formatCurrencyGBP(value)
                          : formatCurrencyGBP(Number(value))
                      }
                      labelFormatter={(name) =>
                        formatLabelName(String(name))
                      }
                    />
                  </PieChart>
                ) : chartType === "horizontalBar" ? (
                  <BarChart
                    data={chartData.data}
                    margin={{ left: 24, right: 16, top: 5, bottom: 60 }}
                  >
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis
                      dataKey="name"
                      angle={-45}
                      textAnchor="end"
                      interval={0}
                      height={70}
                      tick={{ fontSize: 12 }}
                      tickFormatter={(value) =>
                        truncateLabel(formatLabelName(String(value)), 12)
                      }
                    />
                    <YAxis
                      width={72}
                      tickFormatter={(value) =>
                        formatCurrencyGBPCompact(Number(value))
                      }
                      tick={{ fontSize: 12 }}
                    />
                    <Tooltip
                      formatter={(value: number | string) =>
                        typeof value === "number"
                          ? formatCurrencyGBP(value)
                          : formatCurrencyGBP(Number(value))
                      }
                      labelFormatter={(name) =>
                        formatLabelName(String(name))
                      }
                    />
                    <Bar dataKey="value">
                      {chartData.data?.map((entry: any, index: number) => (
                        <Cell
                          key={`cell-${index}`}
                          fill={entry.color || COLORS[index % COLORS.length]}
                        />
                      ))}
                    </Bar>
                  </BarChart>
                ) : chartType === "bar" ? (
                  <BarChart
                    data={chartData.data}
                    margin={{ left: 24, right: 16, top: 5, bottom: 70 }}
                  >
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis
                      dataKey="name"
                      angle={-45}
                      textAnchor="end"
                      interval={0}
                      height={80}
                      tick={{ fontSize: 12 }}
                      tickFormatter={(value) =>
                        truncateLabel(formatLabelName(String(value)), 12)
                      }
                    />
                    <YAxis
                      width={72}
                      tickFormatter={(value) =>
                        formatCurrencyGBPCompact(Number(value))
                      }
                      tick={{ fontSize: 12 }}
                    />
                    <Tooltip
                      formatter={(value: number | string) =>
                        typeof value === "number"
                          ? formatCurrencyGBP(value)
                          : formatCurrencyGBP(Number(value))
                      }
                      labelFormatter={(name) =>
                        formatLabelName(String(name))
                      }
                    />
                    <Bar
                      dataKey="value"
                      fill={chartData.color || COLORS[0]}
                    />
                  </BarChart>
                ) : (
                  <LineChart
                    data={chartData.data}
                    margin={{ left: 24, right: 16, top: 5, bottom: 20 }}
                  >
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey={chartData.xKey || "year"} />
                    <YAxis
                      width={72}
                      tickFormatter={(value) =>
                        formatCurrencyGBPCompact(Number(value))
                      }
                      tick={{ fontSize: 12 }}
                    />
                    <Tooltip
                      formatter={(value: number | string) =>
                        typeof value === "number"
                          ? formatCurrencyGBP(value)
                          : formatCurrencyGBP(Number(value))
                      }
                      labelFormatter={(name) =>
                        formatLabelName(String(name))
                      }
                    />
                    <Line
                      type="monotone"
                      dataKey="value"
                      stroke={COLORS[0]}
                      strokeWidth={2}
                    />
                  </LineChart>
                )}
              </ResponsiveContainer>

              {/* Legend for pie/donut charts (kept consistent; slice labels are disabled) */}
              {(chartType === "pie" || chartType === "donut") && (
                <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {(() => {
                    const total = chartData.data.reduce(
                      (sum: number, item: any) => sum + Number(item.value || 0),
                      0,
                    );
                    return chartData.data.map((entry: any, idx: number) => {
                      const value = Number(entry.value || 0);
                      const pct = total > 0 ? (value / total) * 100 : 0;
                      return (
                        <div
                          key={String(entry.name)}
                          className="flex items-center justify-between gap-3 text-sm"
                        >
                          <div className="flex items-center gap-2 min-w-0">
                            <div
                              className="w-3 h-3 rounded-full flex-none"
                              style={{
                                backgroundColor:
                                  entry.color || COLORS[idx % COLORS.length],
                              }}
                            />
                            <span className="text-gray-700 truncate">
                              {formatLabelName(String(entry.name))}
                            </span>
                          </div>
                          <span className="text-gray-500 flex-none">
                            {pct.toFixed(1)}%
                          </span>
                        </div>
                      );
                    });
                  })()}
                </div>
              )}
            </div>
          );
        })}
      </div>
    );
  };

  /**
   * renderRetirement
   *
   * Renders the "Retirement Projection" tab using Markdown content
   * produced by the retirement planner agent.
   */
  const renderRetirement = () => {
    const retirement = job?.retirement_payload;
    if (!retirement) {
      return (
        <div className="text-center py-12 text-gray-500">
          No retirement projection available.
        </div>
      );
    }

    const retirementAnalysis = retirement.analysis;

    return (
      <div className="space-y-8">
        {retirementAnalysis && (
          <div className="bg-ai-accent/10 border border-ai-accent/20 rounded-lg p-6">
            <MarkdownPanel content={retirementAnalysis} />
          </div>
        )}
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Analysis - Alex AI Financial Advisor</title>
      </Head>

      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            {/* Header */}
            <div className="bg-white rounded-lg shadow px-8 py-6 mb-8">
              <div className="flex items-center justify-between">
                <div>
                  <h1 className="text-3xl font-bold text-dark mb-2">
                    Portfolio Analysis Results
                  </h1>
                  <p className="text-gray-600">
                    Completed on {formatDate(job.created_at)}
                  </p>
                </div>
                <button
                  onClick={() => router.push("/advisor-team")}
                  className="px-6 py-3 bg-ai-accent text-white rounded-lg hover:bg-purple-700 font-semibold"
                >
                  New Analysis
                </button>
              </div>
            </div>

            {/* Tabs */}
            <div className="bg-white rounded-lg shadow mb-8">
              <div className="border-b border-gray-200">
                <nav className="flex -mb-px">
                  <button
                    onClick={() => setActiveTab("overview")}
                    className={`py-3 px-8 border-b-2 font-medium text-sm transition-colors ${
                      activeTab === "overview"
                        ? "border-primary text-primary"
                        : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
                    }`}
                  >
                    Overview
                  </button>
                  <button
                    onClick={() => setActiveTab("charts")}
                    className={`py-3 px-8 border-b-2 font-medium text-sm transition-colors ${
                      activeTab === "charts"
                        ? "border-primary text-primary"
                        : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
                    }`}
                  >
                    Charts
                  </button>
                  <button
                    onClick={() => setActiveTab("retirement")}
                    className={`py-3 px-8 border-b-2 font-medium text-sm transition-colors ${
                      activeTab === "retirement"
                        ? "border-primary text-primary"
                        : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
                    }`}
                  >
                    Retirement Projection
                  </button>
                </nav>
              </div>
            </div>

            {/* Tab Content */}
            <div className="bg-white rounded-lg shadow px-8 py-6">
              {activeTab === "overview" && renderOverview()}
              {activeTab === "charts" && renderCharts()}
              {activeTab === "retirement" && renderRetirement()}
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
