/* eslint-disable @typescript-eslint/no-explicit-any */
/**
 * Analysis Page
 *
 * This page displays the results of a completed portfolio analysis job.
 * It can:
 *  - Load a specific job by `job_id` (from the query string), or
 *  - Automatically find and load the latest completed job if no `job_id` is given.
 *
 * The UI provides:
 *  - A rich Markdown-based overview report
 *  - Dynamic charts generated by the Charter agent (via Recharts)
 *  - A retirement projection view rendered from Markdown
 */

import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import { useAuth } from "@clerk/nextjs";
import ReactMarkdown from "react-markdown";
import type { Components } from "react-markdown";
import remarkGfm from "remark-gfm";
import remarkBreaks from "remark-breaks";
import {
  PieChart,
  Pie,
  Cell,
  BarChart,
  Bar,
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import Layout from "../components/Layout";
import { apiRequest } from "../lib/api";
import Head from "next/head";

/**
 * Job
 *
 * Represents a full analysis job including optional payloads from
 * different agents (report, charts, retirement) and error information.
 */
interface Job {
  id: string;
  created_at: string;
  status: string;
  job_type: string;
  report_payload?: {
    agent: string;
    content: string;
    generated_at: string;
    recommendations?: Array<{
      recommendation: string;
      reasoning: string;
      priority: string;
    }>;
    audit?: {
      model_used?: string;
      duration_ms?: number;
      input_hash?: string;
    };
  };
  // Charter stores charts with dynamic keys and arbitrary payload structures
  charts_payload?: Record<string, any> | null;
  retirement_payload?: {
    agent: string;
    analysis: string;
    generated_at: string;
    metrics?: Record<string, any>;
    action_items?: Array<{ timeframe: string; action: string }>;
    audit?: {
      model_used?: string;
      duration_ms?: number;
    };
  };
  summary_payload?: Record<string, any> | null;
  error_message?: string;
}

/**
 * JobListItem
 *
 * Lightweight representation of a job used when listing and
 * selecting the latest completed job.
 */
interface JobListItem {
  id: string;
  created_at: string;
  status: string;
  job_type: string;
}

/**
 * TabType
 *
 * Controls which main section of the analysis page is visible.
 */
type TabType = "overview" | "charts" | "retirement" | "rebalance";

type CurrencyCode = "GBP" | "USD";

type DataQuality = {
  confidence?: "high" | "medium" | "low" | string;
  counts?: {
    missing_prices?: number;
    missing_allocations?: number;
    stale_prices?: number;
  };
  latest?: {
    instrument_updated_at?: string | null;
    positions_as_of?: string | null;
  };
  details?: Record<string, any>;
};

/**
 * COLORS
 *
 * Shared colour palette used to render Recharts chart components.
 */
const COLORS = [
  "#209DD7", // primary
  "#753991", // AI accent
  "#FFB707", // accent
  "#062147", // dark
  "#60A5FA", // light blue
  "#A78BFA", // light purple
  "#FBBF24", // yellow
  "#34D399", // green
  "#F87171", // red
  "#94A3B8", // gray
];

/**
 * Format numeric values as GBP currency (2 decimal places).
 */
const formatCurrencyGBP = (value: number): string =>
  new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);

const formatCurrency = (value: number, currency: CurrencyCode): string =>
  new Intl.NumberFormat(currency === "USD" ? "en-US" : "en-GB", {
    style: "currency",
    currency,
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(value);

const formatCurrencyGBPCompact = (value: number): string =>
  new Intl.NumberFormat("en-GB", {
    style: "currency",
    currency: "GBP",
    notation: "compact",
    maximumFractionDigits: 1,
  }).format(value);

const truncateLabel = (value: string, max = 14): string =>
  value.length > max ? `${value.slice(0, Math.max(0, max - 1))}…` : value;

/**
 * Convert keys like "fixed_income" or "cash" into "Fixed Income" / "Cash".
 */
const formatLabelName = (name: string): string =>
  name
    .replace(/_/g, " ")
    .split(" ")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
  .join(" ");

const humanizeUnderscoreTokens = (text: string): string =>
  text.replace(/\b[a-z]+(?:_[a-z]+)+\b/g, (match) => formatLabelName(match));

/**
 * Shared Markdown renderer styles.
 *
 * Keeps Overview + Retirement tabs visually consistent.
 */
const MARKDOWN_COMPONENTS: Components = {
  h1: ({ children, ...props }) => (
    <h1
      {...props}
      className="text-3xl font-bold mb-4 text-gray-900 border-b border-gray-300/40 pb-2"
    >
      {children}
    </h1>
  ),
  h2: ({ children, ...props }) => (
    <h2
      {...props}
      className="text-2xl font-semibold mb-3 text-gray-800 mt-6 border-b border-gray-200/40 pb-2"
    >
      {children}
    </h2>
  ),
  h3: ({ children, ...props }) => (
    <h3 {...props} className="text-xl font-medium mb-2 text-gray-700 mt-4">
      {children}
    </h3>
  ),
  ul: ({ children, ...props }) => (
    <ul {...props} className="list-disc ml-6 mb-4 space-y-1">
      {children}
    </ul>
  ),
  ol: ({ children, ...props }) => (
    <ol {...props} className="list-decimal ml-6 mb-4 space-y-1">
      {children}
    </ol>
  ),
  li: ({ children, ...props }) => (
    <li {...props} className="text-gray-700">
      {children}
    </li>
  ),
  p: ({ children, ...props }) => (
    <p {...props} className="mb-4 text-gray-700 leading-relaxed">
      {children}
    </p>
  ),
  table: ({ children, ...props }) => (
    <div className="overflow-x-auto mb-6">
      <table {...props} className="w-full border-collapse">
        {children}
      </table>
    </div>
  ),
  thead: ({ children, ...props }) => (
    <thead {...props} className="!bg-gray-800 !text-gray-100">
      {children}
    </thead>
  ),
  th: ({ children, ...props }) => (
    <th
      {...props}
      className="p-3 text-left font-semibold border border-gray-700 !text-gray-100"
    >
      {children}
    </th>
  ),
  td: ({ children, ...props }) => (
    <td {...props} className="p-3 border border-gray-700">
      {children}
    </td>
  ),
  strong: ({ children, ...props }) => (
    <strong {...props} className="font-semibold text-gray-900">
      {children}
    </strong>
  ),
  blockquote: ({ children, ...props }) => (
    <blockquote
      {...props}
      className="border-l-4 border-primary pl-4 my-4 italic text-gray-600"
    >
      {children}
    </blockquote>
  ),
};

const MarkdownPanel = ({ content }: { content: string }) => (
  <div className="prose prose-lg max-w-none">
    <ReactMarkdown
      remarkPlugins={[remarkGfm, remarkBreaks]}
      components={MARKDOWN_COMPONENTS}
    >
      {content}
    </ReactMarkdown>
  </div>
);

const TAB_TITLES: Record<TabType, string> = {
  overview: "Overview",
  charts: "Charts",
  retirement: "Retirement Projection",
  rebalance: "Rebalancing",
};

const safeNumber = (value: any): number => {
  const n = Number(value);
  return Number.isFinite(n) ? n : 0;
};

const pct = (numerator: number, denominator: number): string => {
  if (!denominator || denominator <= 0) return "0.0%";
  return `${((numerator / denominator) * 100).toFixed(1)}%`;
};

/**
 * Analysis
 *
 * Main page component that:
 *  - Loads a specific analysis job (or the latest completed one)
 *  - Handles loading, empty, in-progress, and failed states
 *  - Renders three main tabs: Overview (Markdown), Charts (Recharts), Retirement projection
 */
export default function Analysis() {
  const router = useRouter();
  const { getToken } = useAuth();
  const { job_id } = router.query;

  const [job, setJob] = useState<Job | null>(null);
  const [loading, setLoading] = useState(true);
  const [activeTab, setActiveTab] = useState<TabType>("overview");
  const [fetchingLatest, setFetchingLatest] = useState(false);
  const [dataQuality, setDataQuality] = useState<DataQuality | null>(null);
  const [rebalancePreview, setRebalancePreview] = useState<any | null>(null);
  const [retirementPreview, setRetirementPreview] = useState<any | null>(null);
  const [scenarioLoading, setScenarioLoading] = useState(false);
  const [rebalanceLoading, setRebalanceLoading] = useState(false);
  const [rebalanceForm, setRebalanceForm] = useState({
    cashOnly: true,
    allowSells: false,
    allowTaxableSells: true,
    driftBandPct: 5,
    maxTurnoverPct: 20,
    transactionCostBps: 10,
    persist: false,
  });
  const [retirementForm, setRetirementForm] = useState({
    annualContribution: 10000,
    yearsUntilRetirement: "",
    retirementAge: "",
    inflationRate: 0.03,
    returnShift: 0.0,
    volatilityMult: 1.0,
    shockYear: "",
    shockPct: "",
    numSimulations: 500,
  });

  const triggerPrint = () => {
    requestAnimationFrame(() => requestAnimationFrame(() => window.print()));
  };

  const escapeMd = (value: string): string =>
    value.replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();

  const buildSummaryMarkdown = (tab: TabType): string => {
    if (!job) return "";

    const charts = job.charts_payload || {};
    const assetClass = charts.asset_class_allocation?.data || [];
    const topHoldings = charts.top_holdings?.data || [];
    const accountValues = charts.account_values?.data || [];

    const totalValue = assetClass.reduce(
      (sum: number, item: any) => sum + safeNumber(item?.value),
      0,
    );
    const cashValue =
      assetClass.find((d: any) => String(d?.name || "").toLowerCase() === "cash")
        ?.value ?? 0;
    const equityValue =
      assetClass.find(
        (d: any) => String(d?.name || "").toLowerCase() === "equity",
      )?.value ?? 0;
    const topHoldingValue = safeNumber(topHoldings?.[0]?.value);
    const numAccounts = Array.isArray(accountValues) ? accountValues.length : 0;

    const overviewRecs = job.report_payload?.recommendations || [];
    const retirementMetrics =
      (retirementPreview?.metrics as any) ?? job.retirement_payload?.metrics ?? null;
    const retirementActions = job.retirement_payload?.action_items || [];
    const rebalance = rebalancePreview ?? job.summary_payload?.rebalance ?? null;
    const rebalanceTrades: any[] = Array.isArray(rebalance?.trades)
      ? rebalance.trades
      : [];

    const takeaways: string[] = [];
    const nextActions: string[] = [];

    if (tab === "overview") {
      takeaways.push(`Cash: ${pct(safeNumber(cashValue), totalValue)}`);
      takeaways.push(`Equity: ${pct(safeNumber(equityValue), totalValue)}`);
      takeaways.push(`Top holding concentration: ${pct(topHoldingValue, totalValue)}`);
      takeaways.push(`Accounts: ${numAccounts}`);
      if (dataQuality?.confidence) {
        takeaways.push(
          `Data quality: ${String(dataQuality.confidence)} (missing prices: ${
            dataQuality.counts?.missing_prices ?? 0
          }, missing allocations: ${dataQuality.counts?.missing_allocations ?? 0})`,
        );
      }
      if (dataQuality?.latest?.instrument_updated_at) {
        takeaways.push(
          `Prices updated: ${new Date(
            dataQuality.latest.instrument_updated_at,
          ).toLocaleString("en-US")}`,
        );
      }

      for (const r of overviewRecs.slice(0, 6)) {
        nextActions.push(`${r.priority || "-"}: ${r.recommendation}`);
      }
      if (overviewRecs.length === 0) nextActions.push("No structured recommendations found in this report.");
    } else if (tab === "retirement") {
      const successRate = safeNumber(retirementMetrics?.monte_carlo?.success_rate);
      const expectedAtRet = safeNumber(
        retirementMetrics?.monte_carlo?.expected_value_at_retirement,
      );
      const gap = safeNumber(retirementMetrics?.safe_withdrawal?.gap);
      takeaways.push(`Success rate: ${successRate.toFixed(1)}%`);
      takeaways.push(`Expected value at retirement: ${expectedAtRet ? expectedAtRet.toLocaleString("en-US") : "-"}`);
      takeaways.push(`4% rule income gap: ${gap ? gap.toLocaleString("en-US") : "-"}`);
      if (dataQuality?.confidence) takeaways.push(`Data quality: ${String(dataQuality.confidence)}`);

      for (const a of retirementActions.slice(0, 6)) {
        nextActions.push(`${a.timeframe}: ${a.action}`);
      }
      if (retirementActions.length === 0) nextActions.push("Review the timeline section in the report.");
    } else if (tab === "rebalance") {
      const currency: CurrencyCode =
        String(rebalance?.jurisdiction || "").toUpperCase() === "US" ? "USD" : "GBP";
      const estCost = safeNumber(rebalance?.estimated_transaction_cost);
      takeaways.push(`Suggested trades: ${rebalanceTrades.length}`);
      takeaways.push(`Estimated transaction cost: ${estCost ? formatCurrency(estCost, currency) : "-"}`);
      takeaways.push(
        `Approach: ${
          rebalance?.options?.cash_only === false ? "May include sells" : "Cash-first"
        }`,
      );
      if (rebalance?.confidence) takeaways.push(`Confidence: ${String(rebalance.confidence)}`);

      for (const t of rebalanceTrades.slice(0, 8)) {
        nextActions.push(
          `${String(t.action || "").toUpperCase()} ${t.symbol} (${t.company || "-"})`,
        );
      }
      if (rebalanceTrades.length === 0) nextActions.push("No trades suggested.");
    } else if (tab === "charts") {
      takeaways.push(`Top holding concentration: ${pct(topHoldingValue, totalValue)}`);
      takeaways.push(`Cash: ${pct(safeNumber(cashValue), totalValue)}`);
      takeaways.push(`Charts available: ${Object.keys(charts || {}).length}`);
      nextActions.push("Review concentration and diversification charts.");
      nextActions.push("Use the Overview tab to act on recommendations.");
    }

    const summaryMd = [
      "## Summary",
      "",
      "### Key Takeaways",
      ...(takeaways.length ? takeaways.map((t) => `- ${t}`) : ["- -"]),
      "",
      "### Next Actions",
      ...(nextActions.length ? nextActions.map((t) => `- ${t}`) : ["- -"]),
      "",
    ].join("\n");

    return summaryMd;
  };

  const buildSummaryData = (
    tab: TabType,
  ): { takeaways: string[]; nextActions: string[] } => {
    if (!job) return { takeaways: [], nextActions: [] };

    // Parse the markdown generated by buildSummaryMarkdown so we don't duplicate business logic.
    const md = buildSummaryMarkdown(tab);
    const lines = md.split("\n").map((l) => l.trim());

    const takeaways: string[] = [];
    const nextActions: string[] = [];
    let mode: "takeaways" | "actions" | null = null;

    for (const line of lines) {
      const lower = line.toLowerCase();
      if (lower === "### key takeaways") {
        mode = "takeaways";
        continue;
      }
      if (lower === "### next actions") {
        mode = "actions";
        continue;
      }
      if (!line.startsWith("- ")) continue;
      const item = line.slice(2).trim();
      if (!item || item === "-") continue;
      if (mode === "takeaways") takeaways.push(item);
      if (mode === "actions") nextActions.push(item);
    }

    return { takeaways, nextActions };
  };

  const SummaryCards = ({ tab }: { tab: TabType }) => {
    const { takeaways, nextActions } = buildSummaryData(tab);

    return (
      <div className="mb-8">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="rounded-xl border border-gray-700 bg-gray-900/30 p-6">
            <h3 className="text-xl font-semibold mb-3 text-gray-100">Key Takeaways</h3>
            <ul className="list-disc pl-6 space-y-2 text-gray-200">
              {takeaways.length ? takeaways.map((t, idx) => <li key={`tk-${idx}`}>{t}</li>) : <li>-</li>}
            </ul>
          </div>
          <div className="rounded-xl border border-gray-700 bg-gray-900/30 p-6">
            <h3 className="text-xl font-semibold mb-3 text-gray-100">Next Actions</h3>
            <ul className="list-disc pl-6 space-y-2 text-gray-200">
              {nextActions.length ? nextActions.map((t, idx) => <li key={`na-${idx}`}>{t}</li>) : <li>-</li>}
            </ul>
          </div>
        </div>
      </div>
    );
  };

  const snakeToTitle = (value: string): string =>
    value
      .replace(/_/g, " ")
      .split(" ")
      .filter(Boolean)
      .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
      .join(" ");

  const formatAuditKey = (key: string): string => {
    const parts = key.split(".").filter(Boolean);
    const fixups: Record<string, string> = {
      id: "ID",
      ms: "ms",
      url: "URL",
      jwt: "JWT",
      jwks: "JWKS",
      sqs: "SQS",
      aws: "AWS",
      cors: "CORS",
    };
    return parts
      .map((p) => {
        const raw = snakeToTitle(p);
        const words = raw.split(" ").map((w) => fixups[w.toLowerCase()] ?? w);
        return words.join(" ");
      })
      .join(" / ");
  };

  const normalizeSectionHeadings = (md: string, tab: TabType): string => {
    if (!md) return md;

    const common = [
      "Executive Summary",
      "Portfolio Composition Analysis",
      "Diversification Assessment",
      "Risk Profile Evaluation",
      "Retirement Readiness",
      "Market Context",
      "Specific Recommendations",
      "Conclusion",
    ];

    const retirement = [
      "Retirement Readiness Summary",
      "Current Situation",
      "Retirement Income Projections",
      "Monte Carlo Simulation Results",
      "Safe Withdrawal Rate Analysis",
      "Specific Recommendations to Improve the Success Rate",
      "Risk Mitigation Strategies",
      "Action Items with a Realistic Timeline",
    ];

    const rebalance = ["Allocation (Asset Class)", "Suggested Trades", "Notes"];

    const headings =
      tab === "retirement"
        ? [...retirement, ...common]
        : tab === "rebalance"
          ? [...rebalance]
          : [...common];

    const set = new Set(headings.map((h) => h.toLowerCase()));
    const lines = md.split("\n");

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i];
      const trimmed = String(line ?? "").trim();
      if (!trimmed) continue;
      if (trimmed.startsWith("#")) continue;

      const lower = trimmed.replace(/:$/, "").toLowerCase();
      if (!set.has(lower)) continue;

      const prevBlank = i === 0 ? true : !String(lines[i - 1] ?? "").trim();
      if (!prevBlank) continue;

      lines[i] = `## ${trimmed.replace(/:$/, "")}`;
    }

    return lines.join("\n");
  };

  const splitForEmbeddedSummary = (md: string): { before: string; after: string } => {
    if (!md) return { before: "", after: "" };

    const execIdx = md.search(/^##\s+.*(executive\s+summary|summary).*$/im);
    const anchorIdx = execIdx >= 0 ? execIdx : md.search(/^#\s+/m);
    if (anchorIdx < 0) return { before: "", after: md };
    const lineEnd = md.indexOf("\n", anchorIdx);
    if (lineEnd < 0) return { before: md, after: "" };
    const splitAt = lineEnd + 1;
    return { before: md.slice(0, splitAt), after: md.slice(splitAt) };
  };

  const buildAuditMarkdown = (tab: TabType): string => {
    if (!job) return "";

    const base = {
      job_created_at: job.created_at,
      job_id: job.id,
    };

    const payload =
      tab === "overview"
        ? {
            generated_at: job.report_payload?.generated_at,
            agent: job.report_payload?.agent,
            audit: job.report_payload?.audit,
            ...base,
          }
        : tab === "retirement"
          ? {
              generated_at: job.retirement_payload?.generated_at,
              agent: job.retirement_payload?.agent,
              audit: job.retirement_payload?.audit,
              assumptions:
                (retirementPreview?.metrics as any)?.assumptions ??
                job.retirement_payload?.metrics?.assumptions,
              scenario_preview_applied: Boolean(retirementPreview),
              ...base,
            }
          : tab === "rebalance"
            ? {
                agent: "rebalancer",
                rebalance_options:
                  (rebalancePreview as any)?.options ??
                  job.summary_payload?.rebalance?.options,
                preview_applied: Boolean(rebalancePreview),
                ...base,
              }
            : {
                agent: "charter",
                chart_keys: Object.keys(job.charts_payload || {}),
                ...base,
              };

    const flatten = (
      obj: Record<string, any>,
      prefix = "",
    ): Array<[string, string]> => {
      const rows: Array<[string, string]> = [];
      for (const [k, v] of Object.entries(obj || {})) {
        const key = prefix ? `${prefix}.${k}` : k;
        if (v && typeof v === "object" && !Array.isArray(v) && Object.keys(v).length <= 12) {
          // Expand a few known nested structures for readability.
          if (k === "audit" || k === "assumptions" || k === "rebalance_options") {
            rows.push(...flatten(v as Record<string, any>, key));
            continue;
          }
        }
        const val =
          v == null
            ? "-"
            : typeof v === "string" || typeof v === "number" || typeof v === "boolean"
              ? String(v)
              : Array.isArray(v)
                ? v.map((x) => (typeof x === "string" ? x : JSON.stringify(x))).join(", ")
                : JSON.stringify(v);
        rows.push([key, val]);
      }
      return rows;
    };

    const rows = flatten(payload as Record<string, any>)
      .map(([k, v]) => `| ${escapeMd(formatAuditKey(k))} | ${escapeMd(v)} |`)
      .join("\n");

    const auditMd = [
      "## Assumptions & Audit",
      "",
      "| Item | Value |",
      "|---|---|",
      rows || "| - | - |",
      "",
    ].join("\n");

    return auditMd;
  };

  const readSessionJson = <T,>(key: string): T | null => {
    if (typeof window === "undefined") return null;
    try {
      const raw = window.sessionStorage.getItem(key);
      if (!raw) return null;
      return JSON.parse(raw) as T;
    } catch {
      return null;
    }
  };

  const writeSessionJson = (key: string, value: unknown) => {
    if (typeof window === "undefined") return;
    try {
      window.sessionStorage.setItem(key, JSON.stringify(value));
    } catch {
      // Ignore storage quota / serialization errors
    }
  };

  /**
   * loadJob
   *
   * Fetches the full details of a single job from the backend.
   */
  useEffect(() => {
    const loadJob = async (jobId: string) => {
      try {
        const token = await getToken();
        if (!token) {
          setLoading(false);
          return;
        }
        const jobData = await apiRequest<Job>(`/api/jobs/${jobId}`, token);
        setJob(jobData);
        setRebalancePreview(null);
        setRetirementPreview(null);
        writeSessionJson(`analysis:job:${jobId}`, jobData);
        writeSessionJson("analysis:latestCompletedJobId", jobId);

        try {
          const cachedDq = readSessionJson<DataQuality>(`analysis:dq:${jobId}`);
          if (cachedDq) setDataQuality(cachedDq);
          const dq = await apiRequest<DataQuality>(
            `/api/jobs/${jobId}/data-quality`,
            token,
          );
          setDataQuality(dq);
          writeSessionJson(`analysis:dq:${jobId}`, dq);
        } catch (err) {
          console.warn("Could not load data quality:", err);
          setDataQuality(null);
        }
      } catch (error) {
        console.error("Error fetching job:", error);
      } finally {
        setLoading(false);
      }
    };

    /**
     * loadLatestJob
     *
     * When no `job_id` is supplied, this function:
     *  - Fetches all jobs
     *  - Finds the latest completed job
     *  - Loads full details for that job
     *  - Updates the URL to include the job_id (shallow replace)
     */
    const loadLatestJob = async () => {
      setFetchingLatest(true);
      try {
        const token = await getToken();
        if (!token) {
          setLoading(false);
          return;
        }

        const cachedLatestId = readSessionJson<string>("analysis:latestCompletedJobId");
        if (cachedLatestId) {
          const cachedJob = readSessionJson<Job>(`analysis:job:${cachedLatestId}`);
          if (cachedJob) {
            setJob(cachedJob);
            setLoading(false);
            router.replace(`/analysis?job_id=${cachedLatestId}`, undefined, {
              shallow: true,
            });
          }
        }
        const data = await apiRequest<{ jobs?: JobListItem[] }>("/api/jobs", token);
        const jobs: JobListItem[] = data.jobs || [];

        const latestCompletedJob = jobs
          .filter((j) => j.status === "completed" && j.job_type === "portfolio_analysis")
          .sort(
            (a, b) =>
              new Date(b.created_at).getTime() -
              new Date(a.created_at).getTime(),
          )[0];

        if (latestCompletedJob) {
          await loadJob(latestCompletedJob.id);

          // Update URL without full page reload
          router.replace(`/analysis?job_id=${latestCompletedJob.id}`, undefined, {
            shallow: true,
          });
        } else {
          setLoading(false);
        }
      } catch (error) {
        console.error("Error fetching latest job:", error);
        setLoading(false);
      } finally {
        setFetchingLatest(false);
      }
    };

    if (job_id) {
      const cachedJob = readSessionJson<Job>(`analysis:job:${job_id as string}`);
      if (cachedJob) {
        setJob(cachedJob);
        setLoading(false);
      }
      // Explicit job_id provided in query
      loadJob(job_id as string);
    } else if (router.isReady) {
      // Router is ready but no job_id â€“ fetch the latest completed analysis
      loadLatestJob();
    }
  }, [job_id, router.isReady, getToken, router]);

  useEffect(() => {
    if (!job) return;

    const reb = job.summary_payload?.rebalance;
    if (reb?.options) {
      setRebalanceForm((prev) => ({
        ...prev,
        cashOnly: Boolean(reb.options.cash_only ?? true),
        allowSells: Boolean(reb.options.cash_only === false),
        allowTaxableSells: Boolean(reb.options.allow_taxable_sells ?? true),
        driftBandPct: Number(reb.options.drift_band_pct ?? 5),
        maxTurnoverPct: Number(reb.options.max_turnover_pct ?? 20),
        transactionCostBps: Number(reb.options.transaction_cost_bps ?? 10),
      }));
    }

    const metrics = job.retirement_payload?.metrics;
    if (metrics) {
      setRetirementForm((prev) => ({
        ...prev,
        annualContribution: Number(metrics.annual_contribution_assumption ?? 10000),
        yearsUntilRetirement: String(metrics.years_until_retirement ?? ""),
        inflationRate: Number(metrics.assumptions?.inflation_rate ?? 0.03),
        returnShift: Number(metrics.assumptions?.return_shift ?? 0.0),
        volatilityMult: Number(metrics.assumptions?.volatility_mult ?? 1.0),
        numSimulations: Number(metrics.assumptions?.num_simulations ?? 500),
      }));
    }
  }, [job]);

  /**
   * formatDate
   *
   * Formats a date string into a long, human-readable format
   * suitable for a "Completed on" label.
   */
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleString("en-US", {
      month: "long",
      day: "numeric",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });
  };

  /**
   * Global loading state: skeleton placeholder while fetching job data.
   */
  if (loading) {
    return (
      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-white rounded-lg shadow px-8 py-12 text-center">
              <div className="animate-pulse">
                <div className="h-8 bg-gray-200 rounded w-1/3 mx-auto mb-4" />
                <div className="h-4 bg-gray-200 rounded w-1/2 mx-auto" />
              </div>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  /**
   * No job available:
   *  - Either there are no completed jobs
   *  - Or the latest job could not be loaded
   */
  if (!job) {
    return (
      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-white rounded-lg shadow px-8 py-12 text-center">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                {fetchingLatest
                  ? "Loading Latest Analysis..."
                  : "No Analysis Available"}
              </h2>
              <p className="text-gray-600 mb-6">
                {fetchingLatest
                  ? "Please wait while we load your latest analysis."
                  : "You have not completed any analyses yet. Start a new analysis to see results here."}
              </p>
              {!fetchingLatest && (
                <button
                  onClick={() => router.push("/advisor-team")}
                  className="px-6 py-3 bg-primary text-white rounded-lg hover:bg-blue-600 font-semibold"
                >
                  Start New Analysis
                </button>
              )}
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  /**
   * In-progress job state:
   *  - Show a status message and simple animated indicators
   */
  if (job.status === "running" || job.status === "pending") {
    return (
      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-white rounded-lg shadow px-8 py-12 text-center">
              <h2 className="text-2xl font-bold text-gray-900 mb-4">
                Analysis In Progress
              </h2>
              <p className="text-gray-600 mb-6">
                Your analysis is still being processed. Please check back in a
                few moments.
              </p>
              <div className="flex justify-center space-x-2 mb-6">
                <div className="w-3 h-3 bg-ai-accent rounded-full animate-pulse" />
                <div className="w-3 h-3 bg-ai-accent rounded-full animate-pulse delay-75" />
                <div className="w-3 h-3 bg-ai-accent rounded-full animate-pulse delay-150" />
              </div>
              <button
                onClick={() => window.location.reload()}
                className="px-6 py-3 bg-primary text-white rounded-lg hover:bg-blue-600 font-semibold"
              >
                Refresh
              </button>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  /**
   * Failed job state:
   *  - Show a failure summary and any error details returned by the backend
   */
  if (job.status === "failed") {
    return (
      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="bg-white rounded-lg shadow px-8 py-12">
              <h2 className="text-2xl font-bold text-red-600 mb-4">
                Analysis Failed
              </h2>
              <p className="text-gray-600 mb-4">
                The analysis encountered an error and could not be completed.
              </p>
              {job.error_message && (
                <div className="bg-red-50 border border-red-200 rounded-lg p-4 mb-6">
                  <p className="text-sm text-red-800">{job.error_message}</p>
                </div>
              )}
              <button
                onClick={() => router.push("/advisor-team")}
                className="px-6 py-3 bg-primary text-white rounded-lg hover:bg-blue-600 font-semibold"
              >
                Try Another Analysis
              </button>
            </div>
          </div>
        </div>
      </Layout>
    );
  }

  /**
   * renderOverview
   *
   * Renders the "Overview" tab using Markdown content from the
   * financial planner agent's report payload.
   */
  const renderOverview = () => {
    const reportRaw = job?.report_payload?.content;
    const report = reportRaw ? humanizeUnderscoreTokens(reportRaw) : reportRaw;
    if (!report) {
      return (
        <div className="text-center py-12 text-gray-500">
          No portfolio report available.
        </div>
      );
    }

    const finalMd = `${report}\n\n${buildAuditMarkdown("overview")}`;
    const normalized = normalizeSectionHeadings(finalMd, "overview");
    const { before, after } = splitForEmbeddedSummary(normalized);
    return (
      <div className="space-y-6">
        {before ? <MarkdownPanel content={before} /> : null}
        <SummaryCards tab="overview" />
        {after ? <MarkdownPanel content={after} /> : null}
      </div>
    );
  };

  /**
   * renderCharts
   *
   * Renders the "Charts" tab using the dynamic charts payload from
   * the Charter agent. It:
   *  - Infers chart type when not explicitly provided
   *  - Supports pie/donut, bar, horizontal bar, and line charts
   *  - Provides responsive containers and formatted tooltips
   */
  const renderCharts = () => {
    const chartsPayload = job?.charts_payload;
    if (!chartsPayload || Object.keys(chartsPayload).length === 0) {
      return (
        <div className="text-center py-12 text-gray-500">
          No chart data available.
        </div>
      );
    }

    const summaryMd = `# Charts\n\n## Executive Summary\n`;

    // Helper to turn a key like "sector_allocation" into "Sector Allocation"
    const formatTitle = (key: string): string => formatLabelName(key);

    /**
     * getChartType
     *
     * Determines which chart type to use based on:
     *  - Explicit `type` field from the charter agent (if present)
     *  - Fallback heuristics based on data shape
     */
    const getChartType = (
      chartData: any,
    ): "pie" | "donut" | "bar" | "horizontalBar" | "line" => {
      if (chartData.type) {
        const supportedTypes = ["pie", "donut", "bar", "horizontalBar", "line"];
        if (supportedTypes.includes(chartData.type)) {
          return chartData.type;
        }

        const typeMap: Record<
          string,
          "pie" | "donut" | "bar" | "horizontalBar" | "line"
        > = {
          column: "bar",
          area: "line",
        };

        if (typeMap[chartData.type]) {
          return typeMap[chartData.type];
        }
      }

      // Simple heuristics when no explicit type is given
      if (chartData.data?.[0]?.date || chartData.data?.[0]?.year) return "line";
      if (chartData.data?.length <= 10 && chartData.data?.[0]?.value)
        return "pie";

      return "bar";
    };

    const chartItems = Object.entries(chartsPayload)
      .map(([key, chartData]) => {
        if (!chartData?.data || chartData.data.length === 0) return null;

        const chartType = getChartType(chartData);
        const title = chartData.title || formatTitle(key);
        const isBar = chartType === "bar" || chartType === "horizontalBar";

        return { key, chartData, chartType, title, isBar };
      })
      .filter(Boolean) as Array<{
      key: string;
      chartData: any;
      chartType: "pie" | "donut" | "bar" | "horizontalBar" | "line";
      title: string;
      isBar: boolean;
    }>;

    const barCharts = chartItems.filter((item) => item.isBar);
    const otherCharts = chartItems.filter((item) => !item.isBar);

    const orderedCharts = [
      ...barCharts.slice(0, 1),
      ...otherCharts,
      ...barCharts.slice(1),
    ];

    return (
      <div className="space-y-6">
        <MarkdownPanel content={summaryMd} />
        <SummaryCards tab="charts" />
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {orderedCharts.map(({ key, chartData, chartType, title, isBar }) => {
            const plotHeight = isBar ? 320 : 300;
            return (
              <div
                key={key}
                className={`bg-white rounded-lg p-6 border border-gray-200 ${
                  isBar ? "lg:col-span-2" : ""
                }`}
              >
              <h3 className="text-xl font-semibold mb-4 text-gray-800">
                {title}
              </h3>
              <ResponsiveContainer width="100%" height={plotHeight}>
                {chartType === "pie" || chartType === "donut" ? (
                  <PieChart>
                    <Pie
                      data={chartData.data}
                      cx="50%"
                      cy="50%"
                      labelLine={false}
                      label={false}
                      outerRadius={100}
                      innerRadius={chartType === "donut" ? 60 : 0}
                      fill="#8884d8"
                      dataKey="value"
                    >
                      {chartData.data.map((entry: any, idx: number) => (
                        <Cell
                          key={`cell-${idx}`}
                          fill={entry.color || COLORS[idx % COLORS.length]}
                        />
                      ))}
                    </Pie>
                    <Tooltip
                      formatter={(value: number | string) =>
                        typeof value === "number"
                          ? formatCurrencyGBP(value)
                          : formatCurrencyGBP(Number(value))
                      }
                      labelFormatter={(name) =>
                        formatLabelName(String(name))
                      }
                    />
                  </PieChart>
                ) : chartType === "horizontalBar" ? (
                  <BarChart
                    data={chartData.data}
                    margin={{ left: 24, right: 16, top: 5, bottom: 60 }}
                  >
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis
                      dataKey="name"
                      angle={-45}
                      textAnchor="end"
                      interval={0}
                      height={70}
                      tick={{ fontSize: 12 }}
                      tickFormatter={(value) =>
                        truncateLabel(formatLabelName(String(value)), 12)
                      }
                    />
                    <YAxis
                      width={72}
                      tickFormatter={(value) =>
                        formatCurrencyGBPCompact(Number(value))
                      }
                      tick={{ fontSize: 12 }}
                    />
                    <Tooltip
                      formatter={(value: number | string) =>
                        typeof value === "number"
                          ? formatCurrencyGBP(value)
                          : formatCurrencyGBP(Number(value))
                      }
                      labelFormatter={(name) =>
                        formatLabelName(String(name))
                      }
                    />
                    <Bar dataKey="value">
                      {chartData.data?.map((entry: any, index: number) => (
                        <Cell
                          key={`cell-${index}`}
                          fill={entry.color || COLORS[index % COLORS.length]}
                        />
                      ))}
                    </Bar>
                  </BarChart>
                ) : chartType === "bar" ? (
                  <BarChart
                    data={chartData.data}
                    margin={{ left: 24, right: 16, top: 5, bottom: 70 }}
                  >
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis
                      dataKey="name"
                      angle={-45}
                      textAnchor="end"
                      interval={0}
                      height={80}
                      tick={{ fontSize: 12 }}
                      tickFormatter={(value) =>
                        truncateLabel(formatLabelName(String(value)), 12)
                      }
                    />
                    <YAxis
                      width={72}
                      tickFormatter={(value) =>
                        formatCurrencyGBPCompact(Number(value))
                      }
                      tick={{ fontSize: 12 }}
                    />
                    <Tooltip
                      formatter={(value: number | string) =>
                        typeof value === "number"
                          ? formatCurrencyGBP(value)
                          : formatCurrencyGBP(Number(value))
                      }
                      labelFormatter={(name) =>
                        formatLabelName(String(name))
                      }
                    />
                    <Bar
                      dataKey="value"
                      fill={chartData.color || COLORS[0]}
                    />
                  </BarChart>
                ) : (
                  <LineChart
                    data={chartData.data}
                    margin={{ left: 24, right: 16, top: 5, bottom: 20 }}
                  >
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey={chartData.xKey || "year"} />
                    <YAxis
                      width={72}
                      tickFormatter={(value) =>
                        formatCurrencyGBPCompact(Number(value))
                      }
                      tick={{ fontSize: 12 }}
                    />
                    <Tooltip
                      formatter={(value: number | string) =>
                        typeof value === "number"
                          ? formatCurrencyGBP(value)
                          : formatCurrencyGBP(Number(value))
                      }
                      labelFormatter={(name) =>
                        formatLabelName(String(name))
                      }
                    />
                    <Line
                      type="monotone"
                      dataKey="value"
                      stroke={COLORS[0]}
                      strokeWidth={2}
                    />
                  </LineChart>
                )}
              </ResponsiveContainer>

              {/* Legend for pie/donut charts (kept consistent; slice labels are disabled) */}
              {(chartType === "pie" || chartType === "donut") && (
                <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-2">
                  {(() => {
                    const total = chartData.data.reduce(
                      (sum: number, item: any) => sum + Number(item.value || 0),
                      0,
                    );
                    return chartData.data.map((entry: any, idx: number) => {
                      const value = Number(entry.value || 0);
                      const pct = total > 0 ? (value / total) * 100 : 0;
                      return (
                        <div
                          key={String(entry.name)}
                          className="flex items-center justify-between gap-3 text-sm"
                        >
                          <div className="flex items-center gap-2 min-w-0">
                            <div
                              className="w-3 h-3 rounded-full flex-none"
                              style={{
                                backgroundColor:
                                  entry.color || COLORS[idx % COLORS.length],
                              }}
                            />
                            <span className="text-gray-700 truncate">
                              {formatLabelName(String(entry.name))}
                            </span>
                          </div>
                          <span className="text-gray-500 flex-none">
                            {pct.toFixed(1)}%
                          </span>
                        </div>
                      );
                    });
                  })()}
                </div>
              )}
              </div>
            );
          })}
        </div>
        <MarkdownPanel content={buildAuditMarkdown("charts")} />
      </div>
    );
  };

  /**
   * renderRetirement
   *
   * Renders the "Retirement Projection" tab using Markdown content
   * produced by the retirement planner agent.
   */
  const renderRetirement = () => {
    const retirement = job?.retirement_payload;
    if (!retirement) {
      return (
        <div className="text-center py-12 text-gray-500">
          No retirement projection available.
        </div>
      );
    }

    const retirementAnalysis =
      typeof (retirement as any)?.analysis === "string"
        ? humanizeUnderscoreTokens((retirement as any).analysis)
        : "";
    const headerMatch = retirementAnalysis.match(/^#\s+.*$/m);
    const headerLine = headerMatch?.[0] || "# Retirement Readiness Assessment";
    const bodyWithoutHeader = headerMatch
      ? retirementAnalysis.replace(headerMatch[0], "").trimStart()
      : retirementAnalysis;

    const introMd = `${headerLine}`;
    const reportBodyMd = bodyWithoutHeader;
    const auditMd = buildAuditMarkdown("retirement");
    const effectiveMetrics =
      (retirementPreview?.metrics as any) ?? job?.retirement_payload?.metrics ?? null;

    const normalizedReport = normalizeSectionHeadings(
      `${introMd}\n\n${reportBodyMd}`,
      "retirement",
    );

    const execIdx = normalizedReport.search(/^##\s+.*(executive\s+summary|summary).*$/im);
    const execLineEnd = execIdx >= 0 ? normalizedReport.indexOf("\n", execIdx) : -1;
    const afterExecStart = execLineEnd >= 0 ? execLineEnd + 1 : -1;
    const nextH2Idx =
      afterExecStart >= 0
        ? (() => {
            const tail = normalizedReport.slice(afterExecStart);
            const rel = tail.search(/^##\s+/m);
            return rel >= 0 ? afterExecStart + rel : -1;
          })()
        : -1;

    const mdBeforeExecLine =
      execIdx >= 0 && execLineEnd >= 0 ? normalizedReport.slice(0, execLineEnd + 1) : introMd;
    const mdExecBody =
      execIdx >= 0 && execLineEnd >= 0
        ? normalizedReport.slice(execLineEnd + 1, nextH2Idx >= 0 ? nextH2Idx : normalizedReport.length)
        : "";
    const mdAfterExec =
      nextH2Idx >= 0 ? normalizedReport.slice(nextH2Idx) : execIdx >= 0 ? "" : normalizedReport.slice(introMd.length);

    return (
      <div className="space-y-8">
        <MarkdownPanel content={mdBeforeExecLine} />
        <SummaryCards tab="retirement" />
        {mdExecBody ? <MarkdownPanel content={mdExecBody} /> : null}

        <div className="no-print">
          <h2 className="text-2xl font-semibold text-gray-800 mb-2">
            Interactive Tools
          </h2>
          <p className="text-gray-600">
            Use these controls to stress-test assumptions and see the impact instantly.
          </p>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6 no-print">
          <h3 className="text-xl font-semibold mb-3 text-gray-800">
            Scenario Planning (Instant)
          </h3>
          <p className="text-gray-600 mb-3">
            Adjust assumptions and recompute retirement success metrics instantly (this
            does not regenerate the narrative text).
          </p>
          <ul className="list-disc ml-6 text-sm text-gray-600 space-y-1 mb-4">
            <li>
              <span className="font-medium">Return shift</span>: adds/subtracts a
              constant from the expected return each year (e.g. -0.02 = -2%/yr).
            </li>
            <li>
              <span className="font-medium">Volatility multiplier</span>: scales
              volatility up/down (e.g. 1.2 = 20% more volatile).
            </li>
            <li>
              <span className="font-medium">Shock year</span>: applies a one-time
              market shock in that simulation year.
            </li>
            <li>
              <span className="font-medium">Shock pct</span>: shock magnitude as a
              fraction (0.25 = -25% drop in that year).
            </li>
          </ul>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <label className="text-sm text-gray-600">
              Annual contribution
              <input
                type="number"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={retirementForm.annualContribution}
                onChange={(e) =>
                  setRetirementForm((p) => ({
                    ...p,
                    annualContribution: Number(e.target.value || 0),
                  }))
                }
              />
            </label>
            <label className="text-sm text-gray-600">
              Years until retirement (optional)
              <input
                type="number"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={retirementForm.yearsUntilRetirement}
                onChange={(e) =>
                  setRetirementForm((p) => ({
                    ...p,
                    yearsUntilRetirement: e.target.value,
                  }))
                }
              />
            </label>
            <label className="text-sm text-gray-600">
              Inflation rate (e.g. 0.03)
              <input
                type="number"
                step="0.001"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={retirementForm.inflationRate}
                onChange={(e) =>
                  setRetirementForm((p) => ({
                    ...p,
                    inflationRate: Number(e.target.value || 0),
                  }))
                }
              />
            </label>
            <label className="text-sm text-gray-600">
              Return shift (e.g. -0.02)
              <input
                type="number"
                step="0.001"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={retirementForm.returnShift}
                onChange={(e) =>
                  setRetirementForm((p) => ({
                    ...p,
                    returnShift: Number(e.target.value || 0),
                  }))
                }
              />
            </label>
            <label className="text-sm text-gray-600">
              Volatility multiplier (e.g. 1.2)
              <input
                type="number"
                step="0.1"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={retirementForm.volatilityMult}
                onChange={(e) =>
                  setRetirementForm((p) => ({
                    ...p,
                    volatilityMult: Number(e.target.value || 1),
                  }))
                }
              />
            </label>
            <label className="text-sm text-gray-600">
              Simulations
              <input
                type="number"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={retirementForm.numSimulations}
                onChange={(e) =>
                  setRetirementForm((p) => ({
                    ...p,
                    numSimulations: Number(e.target.value || 500),
                  }))
                }
              />
            </label>
            <label className="text-sm text-gray-600">
              Shock year (optional)
              <input
                type="number"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={retirementForm.shockYear}
                onChange={(e) =>
                  setRetirementForm((p) => ({
                    ...p,
                    shockYear: e.target.value,
                  }))
                }
              />
            </label>
            <label className="text-sm text-gray-600">
              Shock pct (0-1, optional)
              <input
                type="number"
                step="0.01"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={retirementForm.shockPct}
                onChange={(e) =>
                  setRetirementForm((p) => ({
                    ...p,
                    shockPct: e.target.value,
                  }))
                }
              />
            </label>
          </div>

          <div className="mt-4 flex items-center gap-3">
            <button
              type="button"
              disabled={scenarioLoading}
              onClick={async () => {
                try {
                  setScenarioLoading(true);
                  const token = await getToken();
                  if (!token || !job?.id) return;

                  const body: any = {
                    annual_contribution: Number(retirementForm.annualContribution || 0),
                    inflation_rate: Number(retirementForm.inflationRate || 0),
                    return_shift: Number(retirementForm.returnShift || 0),
                    volatility_mult: Number(retirementForm.volatilityMult || 1),
                    num_simulations: Number(retirementForm.numSimulations || 500),
                  };

                  if (String(retirementForm.yearsUntilRetirement || "").trim() !== "") {
                    body.years_until_retirement = Number(retirementForm.yearsUntilRetirement);
                  }
                  if (String(retirementForm.shockYear || "").trim() !== "") {
                    body.shock_year = Number(retirementForm.shockYear);
                  }
                  if (String(retirementForm.shockPct || "").trim() !== "") {
                    body.shock_pct = Number(retirementForm.shockPct);
                  }

                  const resp = await apiRequest<any>(
                    `/api/jobs/${job.id}/retirement/preview`,
                    token,
                    { method: "POST", body: JSON.stringify(body) },
                  );
                  setRetirementPreview(resp);
                  if (resp?.data_quality) setDataQuality(resp.data_quality);
                } finally {
                  setScenarioLoading(false);
                }
              }}
              className="px-4 py-2 bg-primary text-white rounded-lg hover:bg-blue-600 font-semibold disabled:opacity-50"
            >
              {scenarioLoading ? "Recomputing..." : "Recompute"}
            </button>
            {retirementPreview && (
              <button
                type="button"
                onClick={() => setRetirementPreview(null)}
                className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 font-semibold"
              >
                Reset
              </button>
            )}
          </div>

          {effectiveMetrics && (
            <div className="mt-4 text-sm text-gray-600">
              Preview success rate:{" "}
              <span className="font-semibold">
                {safeNumber(effectiveMetrics?.monte_carlo?.success_rate).toFixed(1)}%
              </span>
            </div>
          )}
        </div>

        {scenarioLoading && (
          <div className="no-print bg-gray-50 border border-gray-200 rounded-lg p-4 animate-pulse text-sm text-gray-600">
            Recomputing scenario metrics…
          </div>
        )}

        {retirementAnalysis ? (
          <>
            {mdAfterExec ? <MarkdownPanel content={mdAfterExec} /> : null}
            <MarkdownPanel content={auditMd} />
          </>
        ) : (
          <div className="text-center py-12 text-gray-500">
            No retirement narrative available (agent may have failed). Check CloudWatch logs for `alex-retirement`.
          </div>
        )}
      </div>
    );
  };

  const renderRebalance = () => {
    const rebalance = rebalancePreview ?? job?.summary_payload?.rebalance;
    if (!rebalance || rebalance.enabled === false) {
      return (
        <div className="text-center py-12 text-gray-500">
          No rebalancing recommendation available.
        </div>
      );
    }

    const currency: CurrencyCode =
      String(rebalance.jurisdiction || "").toUpperCase() === "US" ? "USD" : "GBP";

    const allocation = rebalance.asset_class_allocation || {};
    const currentPct = allocation.current_pct || {};
    const targetPct = allocation.target_pct || {};

    const trades: any[] = Array.isArray(rebalance.trades) ? rebalance.trades : [];
    const notes: string[] = Array.isArray(rebalance.notes) ? rebalance.notes : [];
    const estCost = rebalance.estimated_transaction_cost;

    const fmtPct = (value: any): string => `${Number(value || 0).toFixed(2)}%`;

    const allocationKeys = Array.from(
      new Set([...Object.keys(currentPct), ...Object.keys(targetPct)]),
    );

    const allocationRows = allocationKeys
      .map((k) => `| ${formatLabelName(k)} | ${fmtPct(currentPct[k])} | ${fmtPct(targetPct[k])} |`)
      .join("\n");

    const tradesRows =
      trades.length === 0
        ? "| - | - | - | - | - | - |"
        : trades
            .map((t) => {
              const company = String(t.company || t.symbol || "-");
              const ticker = String(t.symbol || "-");
              const account = String(t.account || "-");
              const action = String(t.action || "").toUpperCase() || "-";
              const estValue = formatCurrency(Number(t.estimated_value || 0), currency);
              const estQty =
                t.estimated_quantity != null
                  ? Number(t.estimated_quantity).toLocaleString("en-US", {
                      maximumFractionDigits: 6,
                    })
                  : "-";
              return `| ${company} | ${ticker} | ${account} | ${action} | ${estValue} | ${estQty} |`;
            })
            .join("\n");

    const cleanedNotes = notes
      .map((n) => String(n || "").trim())
      .filter(Boolean)
      .map((n) => n.replace(/^-+\s*/, ""));

    const md = [
      "# Rebalancing Recommendation",
      "",
      "This tab provides a deterministic rebalancing suggestion. It compares your current asset-class weights to your target weights and suggests example trades to move you closer to target (cash-first where possible).",
      "",
      ...(typeof estCost === "number" && estCost > 0
        ? [`Estimated transaction cost: **${formatCurrency(estCost, currency)}**`, ""]
        : []),
      "## Allocation (Asset Class)",
      "| Asset Class | Current | Target |",
      "|---|---:|---:|",
      allocationRows || "| - | - | - |",
      "",
      "## Suggested Trades",
      "| Company | Ticker | Account | Action | Est. Value | Est. Qty |",
      "|---|---|---|---|---:|---:|",
      tradesRows,
      "",
      "## Notes",
      ...(cleanedNotes.length ? cleanedNotes.map((n) => `- ${n}`) : ["- No additional notes."]),
      "",
    ].join("\n");

    const headerMatch = md.match(/^#\s+.*$/m);
    const headerLine = headerMatch?.[0] || "# Rebalancing Recommendation";
    const bodyWithoutHeader = headerMatch ? md.replace(headerMatch[0], "").trimStart() : md;

    const introMd = `${headerLine}\n\n## Executive Summary\n`;
    const reportMd = `${bodyWithoutHeader}\n\n${buildAuditMarkdown("rebalance")}`;

    return (
      <div className="space-y-6">
        <MarkdownPanel content={introMd} />
        <SummaryCards tab="rebalance" />

        <div className="no-print">
          <h2 className="text-2xl font-semibold text-gray-800 mb-2">
            Interactive Tools
          </h2>
          <p className="text-gray-600">
            Adjust constraints and instantly recompute suggested trades.
          </p>
        </div>

        <div className="bg-white rounded-lg border border-gray-200 p-6 no-print">
          <h3 className="text-xl font-semibold mb-3 text-gray-800">
            Rebalance Settings (Instant)
          </h3>
          <p className="text-gray-600 mb-4">
            Tune rebalancing constraints and recompute suggested trades instantly.
          </p>
          <ul className="list-disc ml-6 text-sm text-gray-600 space-y-1 mb-4">
            <li>
              <span className="font-medium">Cash-only</span>: suggests buys using cash
              only (no sells).
            </li>
            <li>
              <span className="font-medium">Allow sells</span>: permits sells when
              needed to reduce drift.
            </li>
            <li>
              <span className="font-medium">Drift band</span>: rebalances only when an
              asset class is outside this % band from target.
            </li>
            <li>
              <span className="font-medium">Max turnover</span>: caps total trade size
              vs portfolio value.
            </li>
          </ul>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <label className="text-sm text-gray-600 flex items-center gap-2">
              <input
                type="checkbox"
                checked={rebalanceForm.cashOnly}
                onChange={(e) =>
                  setRebalanceForm((p) => ({ ...p, cashOnly: e.target.checked }))
                }
              />
              Cash-only (no sells)
            </label>
            <label className="text-sm text-gray-600 flex items-center gap-2">
              <input
                type="checkbox"
                checked={rebalanceForm.allowSells}
                onChange={(e) =>
                  setRebalanceForm((p) => ({ ...p, allowSells: e.target.checked }))
                }
              />
              Allow sells (if needed)
            </label>
            <label className="text-sm text-gray-600 flex items-center gap-2">
              <input
                type="checkbox"
                checked={rebalanceForm.allowTaxableSells}
                onChange={(e) =>
                  setRebalanceForm((p) => ({
                    ...p,
                    allowTaxableSells: e.target.checked,
                  }))
                }
              />
              Allow taxable sells
            </label>
            <label className="text-sm text-gray-600">
              Drift band (%)
              <input
                type="number"
                step="0.1"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={rebalanceForm.driftBandPct}
                onChange={(e) =>
                  setRebalanceForm((p) => ({
                    ...p,
                    driftBandPct: Number(e.target.value || 0),
                  }))
                }
              />
            </label>
            <label className="text-sm text-gray-600">
              Max turnover (%)
              <input
                type="number"
                step="0.1"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={rebalanceForm.maxTurnoverPct}
                onChange={(e) =>
                  setRebalanceForm((p) => ({
                    ...p,
                    maxTurnoverPct: Number(e.target.value || 0),
                  }))
                }
              />
            </label>
            <label className="text-sm text-gray-600">
              Transaction cost (bps)
              <input
                type="number"
                step="1"
                className="mt-1 w-full rounded border border-gray-300 px-3 py-2"
                value={rebalanceForm.transactionCostBps}
                onChange={(e) =>
                  setRebalanceForm((p) => ({
                    ...p,
                    transactionCostBps: Number(e.target.value || 0),
                  }))
                }
              />
            </label>
          </div>

          <div className="mt-4 flex items-center gap-3">
            <button
              type="button"
              disabled={rebalanceLoading}
              onClick={async () => {
                try {
                  setRebalanceLoading(true);
                  const token = await getToken();
                  if (!token || !job?.id) return;
                  const body: any = {
                    cash_only: Boolean(rebalanceForm.cashOnly),
                    allow_sells: Boolean(rebalanceForm.allowSells),
                    allow_taxable_sells: Boolean(rebalanceForm.allowTaxableSells),
                    drift_band_pct: Number(rebalanceForm.driftBandPct || 0),
                    max_turnover_pct: Number(rebalanceForm.maxTurnoverPct || 0),
                    transaction_cost_bps: Number(rebalanceForm.transactionCostBps || 0),
                    persist: Boolean(rebalanceForm.persist),
                  };
                  const resp = await apiRequest<any>(
                    `/api/jobs/${job.id}/rebalance/preview`,
                    token,
                    { method: "POST", body: JSON.stringify(body) },
                  );
                  setRebalancePreview(resp?.rebalance ?? null);
                  if (resp?.data_quality) setDataQuality(resp.data_quality);
                } finally {
                  setRebalanceLoading(false);
                }
              }}
              className="px-4 py-2 bg-primary text-white rounded-lg hover:bg-blue-600 font-semibold disabled:opacity-50"
            >
              {rebalanceLoading ? "Recomputing..." : "Recompute"}
            </button>
            {rebalancePreview && (
              <button
                type="button"
                onClick={() => setRebalancePreview(null)}
                className="px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700 font-semibold"
              >
                Reset
              </button>
            )}
          </div>
        </div>

        {rebalanceLoading && (
          <div className="no-print bg-gray-50 border border-gray-200 rounded-lg p-4 animate-pulse text-sm text-gray-600">
            Recomputing trade suggestions…
          </div>
        )}

        <MarkdownPanel content={reportMd} />
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Analysis - Alex AI Financial Advisor</title>
      </Head>

      <Layout>
        <div className="min-h-screen bg-gray-50 py-8">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            {/* Header */}
            <div className="bg-white rounded-lg shadow px-8 py-6 mb-8">
              <div className="flex items-center justify-between">
                <div>
                  <h1 className="text-3xl font-bold text-dark mb-2">
                    Portfolio Analysis Results
                  </h1>
                  <p className="text-gray-600">
                    Completed on {formatDate(job.created_at)}
                  </p>
                </div>
                <button
                  onClick={() => router.push("/advisor-team")}
                  className="px-6 py-3 bg-ai-accent text-white rounded-lg hover:bg-purple-700 font-semibold"
                >
                  New Analysis
                </button>
              </div>
            </div>

            {/* Tabs */}
            <div className="bg-white rounded-lg shadow mb-8">
              <div className="border-b border-gray-200">
                <nav className="flex -mb-px">
                  <button
                    onClick={() => setActiveTab("overview")}
                    className={`py-3 px-8 border-b-2 font-medium text-sm transition-colors ${
                      activeTab === "overview"
                        ? "border-primary text-primary"
                        : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
                    }`}
                  >
                    Overview
                  </button>
                  <button
                    onClick={() => setActiveTab("charts")}
                    className={`py-3 px-8 border-b-2 font-medium text-sm transition-colors ${
                      activeTab === "charts"
                        ? "border-primary text-primary"
                        : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
                    }`}
                  >
                    Charts
                  </button>
                  <button
                    onClick={() => setActiveTab("retirement")}
                    className={`py-3 px-8 border-b-2 font-medium text-sm transition-colors ${
                      activeTab === "retirement"
                        ? "border-primary text-primary"
                        : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
                    }`}
                  >
                    Retirement Projection
                  </button>
                  <button
                    onClick={() => setActiveTab("rebalance")}
                    className={`py-3 px-8 border-b-2 font-medium text-sm transition-colors ${
                      activeTab === "rebalance"
                        ? "border-primary text-primary"
                        : "border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300"
                    }`}
                  >
                    Rebalancing
                  </button>
                </nav>
              </div>
            </div>

            {/* Tab Content */}
            <div className="bg-white rounded-lg shadow px-8 py-6">
              <div className="flex items-center justify-between gap-4 mb-6 no-print">
                <div className="text-sm text-gray-500">
                  Export this tab via your browser: Save to PDF.
                </div>
                <button
                  type="button"
                  onClick={() => triggerPrint()}
                  className="px-4 py-2 bg-primary text-white rounded-lg hover:bg-blue-600 font-semibold"
                >
                  Export Tab PDF
                </button>
              </div>

              <div id="print-area">
                <div className="print-only mb-6">
                  <div className="print-header">
                    <div className="text-xs text-gray-600">
                      Alex AI Financial Advisor
                    </div>
                    <div className="text-sm font-semibold text-gray-900">
                      {TAB_TITLES[activeTab]}
                    </div>
                    <div className="text-xs text-gray-600">
                      Job {job.id} · Completed {formatDate(job.created_at)}
                    </div>
                  </div>
                  <div className="print-footer">
                    <div className="text-xs text-gray-500">
                      For informational purposes only · Not financial advice
                    </div>
                  </div>
                  <div className="print-page-content">
                    <h1 className="text-2xl font-bold text-gray-900">
                      {TAB_TITLES[activeTab]}
                    </h1>
                    <p className="text-sm text-gray-600">
                      Completed on {formatDate(job.created_at)}
                    </p>
                  </div>
                </div>

                {activeTab === "overview" && renderOverview()}
                {activeTab === "charts" && renderCharts()}
                {activeTab === "retirement" && renderRetirement()}
                {activeTab === "rebalance" && renderRebalance()}
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </>
  );
}
